context:
  name: visp
  version: 3.7.0

recipe:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/lagadic/visp/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 997f247f3702c83f0a8a6dc2f72ff98cfe3a5dcbd82f7c9f01d37ccd3b8ea97a
  patches:
    # https://github.com/lagadic/visp/pull/1890
    - patches/0001-add-an-option-to-build-python-stubs-or-not.patch
    # Current version of this package do not enable AVX support. The Windows build uses
    # the Clang-cl compiler wich fails to build the embedded Simd library on AVX instructions
    # even when AVX flags are not on for some unknown reason, so we have to force
    # disabling AVX support at the Simd library level.
    - if: win
      then: patches/0010-Disable-AVX-and-AVX2-for-Simd-embedded-lib.patch
    - patches/0001-clang-cl-on-win-does-not-provide-unistd-header.patch

build:
  number: 6

outputs:
  - package:
      name: libvisp
    build:
      script: scripts/build-lib
    requirements:
      build:
        - ${{ compiler('cxx') }}
        - ${{ stdlib('c') }}
        - cmake
        - ninja
        - pkgconfig
      host:
        - if: unix
          then:
            - xorg-libx11
            - xorg-libxfixes
            - xorg-xorgproto
            - libxml2
            - libdc1394 >=2.2.6
            - librealsense
        - if: osx
          then:
            - llvm-openmp
        - libopencv
        - eigen
        - libjpeg-turbo
        - libpng
        - libblas
        - libcblas
        - liblapack
        - liblapacke
        - nlohmann_json
        - panda3d
      run:
        - if: osx
          then: libcxx
        - eigen
      run_exports:
        - ${{ pin_subpackage('libvisp', upper_bound='x.x') }}
    tests:
      - package_contents:
          include:
            - visp3/visp.h
          lib:
            # win libs contains version specific strings that are not available for now from jinja
            # https://github.com/prefix-dev/rattler-build/issues/1068
            - if: unix
              then:
                - visp_core
              else:
                - visp_core*
      - script:
          - cmake-package-check VISP
        requirements:
          run:
            - cmake-package-check
            - ${{ compiler('cxx') }}
      - script:
          - if: unix
            then: visp-config --version
          # Broken with rattler-build
          - if: win
            then:
              - dir
              - call Library\bin\visp-config.bat --version

  - package:
      name: visp-python
    build:
      script: scripts/build-python
    requirements:
      build:
        - if: build_platform != target_platform
          then:
            - python
            - cross-python_${{ target_platform }}
            - numpy
            - pybind11
        - ${{ compiler('cxx') }}
        - ${{ stdlib('c') }}
        - cmake
        - ninja
        - pkgconfig
        - if: win
          then:
            - clang
      host:
        - python
        - numpy
        - pybind11
        - pip
        - setuptools
        - cxxheaderparser
        - doxmlparser
        - pcpp
        - tqdm
        - mypy
        - if: unix
          then:
            - xorg-xorgproto
        - panda3d
        - ${{ pin_subpackage('libvisp', exact=true) }}
      run:
        - python
        - ${{ pin_subpackage('libvisp', exact=true) }}
    tests:
      - python:
          imports:
            - visp

  - package:
      name: ${{ name }}
    requirements:
      run:
        - ${{ pin_subpackage('libvisp', exact=true) }}
        - ${{ pin_subpackage('visp-python', exact=true) }}
      run_exports:
        - ${{ pin_subpackage('libvisp', upper_bound='x.x') }}
    tests:
      - script:
          - cmake-package-check VISP
        requirements:
          run:
            - cmake-package-check
            - ${{ compiler('cxx') }}
      - python:
          imports:
            - visp

about:
  summary: A cross-platform library for prototyping and developing applications using visual tracking and visual servoing technic.
  description: C++ development libraries and Python bidings for ViSP.
  license: GPL-2.0-only
  license_file: LICENSE.txt
  homepage: https://visp.inria.fr/
  repository: https://github.com/lagadic/visp
  documentation: https://visp-doc.inria.fr/doxygen/visp-${{ version }}/

extra:
  recipe-maintainers:
    - rolalaro
    - olivier-roussel
    - fspindle
