context:
  name: visp
  version: 3.6.99

recipe:
  name: ${{ name|lower }}
  version: ${{ version }}

build:
  number: 0

cache:
  source:
    # git: https://github.com/lagadic/visp
    # branch: master
    git: https://github.com/olivier-roussel/visp
    branch: fix-rbt-math-header
    # url: https://github.com/lagadic/visp/archive/refs/tags/v${{ version }}.tar.gz
    # sha256: eec93f56b89fd7c0d472b019e01c3fe03a09eda47f3903c38dc53a27cbfae532
    patches:
      # Current version of this package do not enable AVX support. The Windows build uses
      # the Clang-cl compiler wich fails to build the embedded Simd library on AVX instructions
      # even when AVX flags are not on for some unknown reason, so we have to force
      # disabling AVX support at the Simd library level.
      - if: win
        then: patches/0002-Disable-AVX-and-AVX2-for-Simd-embedded-lib.patch
  build:
    script: scripts/build-cache

  requirements:
    build:
      - ${{ compiler('c') }}
      - ${{ compiler('cxx') }}
      - ${{ stdlib('c') }}
      - cmake
      - ninja
      - pkgconfig
      - if: win
        then:
          - clang
    host:
      - if: unix
        then:
          - xorg-libx11
          - xorg-libxfixes
          - xorg-xorgproto
          - libxml2
          - libdc1394 >=2.2.6
          - librealsense
      - if: osx
        then:
          - llvm-openmp
      - libopencv
      - eigen
      - libjpeg-turbo
      - libpng
      - libblas
      - libcblas
      - liblapack
      - liblapacke
      - nlohmann_json
      - if: not (osx and arm64)
        then:
          - panda3d
    run:
      - if: osx
        then: libcxx
      - eigen

outputs:
  - package:
      name: libvisp
    build:  
      files:
        - ${{ "Library/" if win }}bin/*
        - ${{ "Library/" if win }}lib/${{ "lib" if not win }}visp*
        - ${{ "Library/" if win }}include/*
        - ${{ "Library/" if win }}lib/cmake/visp*
        - ${{ "Library/" if win }}share/*
    requirements:
      run_exports:
        - ${{ pin_subpackage('libvisp', upper_bound='x.x') }}
    tests:
      - package_contents:
          include:
            - visp3/visp.h
          lib:
            # win libs contains version specific strings that are not available for now from jinja
            # https://github.com/prefix-dev/rattler-build/issues/1068
            - if: unix
              then:
                - visp_core
              else:
                - visp_core*
          files:
            - ${{ "Library" if win else "lib" }}/cmake/${{ "visp/" if unix }}VISPConfig.cmake
            - ${{ "Library" if win else "lib" }}/cmake/${{ "visp/" if unix }}VISPConfig-version.cmake
      - script:
          - if: unix
            then: visp-config --version
          # Broken with rattler-build
          - if: win
            then:
              - dir
              - call Library\bin\visp-config.bat --version
    about:
      summary: A cross-platform library for prototyping and developing applications using visual tracking and visual servoing technic.
      license: GPL-2.0-only
      license_file: LICENSE.txt
      homepage: https://visp.inria.fr/
      repository: https://github.com/lagadic/visp
      documentation: https://visp-doc.inria.fr/doxygen/visp-${{ version }}/

  - package:
      name: visp-python
    build:  
      script: scripts/build-python
    requirements:
      build:
        - if: build_platform != target_platform
          then:
            - python
            - cross-python_${{ target_platform }}
            - numpy
        - ${{ compiler('c') }}
        - ${{ compiler('cxx') }}
        - ${{ stdlib('c') }}
        - cmake
        - ninja
        - pkgconfig
        - pip
        - setuptools
        - if: win
          then:
            - clang
      host:
        - python
        - numpy
        - pybind11
        - pip
        - setuptools
        - zlib
        - if: unix
          then:
            - xorg-libx11
            - xorg-libxfixes
            - xorg-xorgproto
        - if: not (osx and arm64)
          then:
            - panda3d            
        - ${{ pin_subpackage('libvisp', exact=true) }}
      run:
        - python
        - ${{ pin_subpackage('libvisp', exact=true) }}
    tests:
      - python:
          imports:
            - visp
    about:
      summary: A cross-platform library for prototyping and developing applications using visual tracking and visual servoing technic.
      license: GPL-2.0-only
      license_file: LICENSE.txt
      homepage: https://visp.inria.fr/
      repository: https://github.com/lagadic/visp
      documentation: https://visp-doc.inria.fr/doxygen/visp-${{ version }}/

extra:
  recipe-maintainers:
    - olivier-roussel
    - fspindle
