# Workaround for https://github.com/conda-forge/opencv-feedstock/issues/493
azure:
  settings_osx:
    pool:
      vmImage: macos-14
build_platform:
  linux_aarch64: linux_64
  osx_arm64: osx_64
conda_build:
  error_overlinking: true
conda_build_tool: rattler-build
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
provider:
  linux_aarch64: default
test: native_and_emulated
